#This is the base image
FROM quoinedev/python3.7-pandas-alpine

#defining the work directory
WORKDIR /usr/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip

#copying requirements.txt to install the requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

#setting the enviornment

#copying everything else
COPY ./ ./

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]